export const optionFilter = [
  { label: 'shirt' },
  { label: 'accessory' },
  { label: 'shoe' },
  { label: 'bag' },
  { label: 'sock' },
];

export const data = [
  {
    productID: 1042669,
    productName: 'Retro Souvenir Ball - The Team',
    productPrice: '550.000 VND',
    promotion: [],
    productColor: 'Brilliant White',
    productSKU: 'FPB001',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_FPB001_1-2-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_FPB001_7-2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 90,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/fpb001/',
    category: 'Football Equipment',
    isBuyOnline: false,
    isLimitedEdition: true,
  },
  {
    productID: 1000492,
    productName: 'Basas Day Slide - Slip On',
    productPrice: '550.000 VND',
    promotion: [],
    productColor: 'Caviar Black',
    productSKU: 'AV00211',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00211_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00211_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 377,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00211/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 1000493,
    productName: 'Basas Day Slide - Slip On',
    productPrice: '550.000 VND',
    promotion: [],
    productColor: 'Offwhite',
    productSKU: 'AV00210',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00210_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00210_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 363,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00210/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992072,
    productName: 'Basic Tee - Branding Label',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Caviar Black',
    productSKU: 'ABT00027',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00027_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00027_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 58,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00027/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992073,
    productName: 'Basic Tee - Branding Label',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Cloud Dancer',
    productSKU: 'ABT00026',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00026_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00026_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 46,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00026/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992069,
    productName: 'Basic Tee - Branding Label',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Frost Gray',
    productSKU: 'ABT00030',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00030_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00030_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 59,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00030/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992071,
    productName: 'Basic Tee - Branding Label',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Grape Compote',
    productSKU: 'ABT00028',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00028_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00028_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 30,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00028/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992070,
    productName: 'Basic Tee - Branding Label',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Medium Green',
    productSKU: 'ABT00029',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00029_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00029_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 39,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00029/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992055,
    productName: 'Basic Tee - Ananas Oval Symbol',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Caviar Black',
    productSKU: 'ABT00022',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00022_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00022_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 58,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00022/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 988591,
    productName: 'Basic Tee - Ananas Oval Symbol',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Cloud Dancer',
    productSKU: 'ABT00021',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00021_1-1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00021_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 15,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00021/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992053,
    productName: 'Basic Tee - Ananas Oval Symbol',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Medium Green',
    productSKU: 'ABT00024',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00024_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00024_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 39,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00024/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992054,
    productName: 'Basic Tee - Ananas Oval Symbol',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Grape Compote',
    productSKU: 'ABT00023',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00023_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00023_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 30,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00023/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 992052,
    productName: 'Basic Tee - Ananas Oval Symbol',
    productPrice: '290.000 VND',
    promotion: [],
    productColor: 'Frost Gray',
    productSKU: 'ABT00025',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ABT00025_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ABT00025_3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 55,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/abt00025/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 1034326,
    productName: 'Urbas Love+ 24',
    productPrice: '650.000 VND',
    promotion: [],
    productColor: 'Oyster White',
    productSKU: 'ALP2401',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ALP2401_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ALP2401_5-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 94,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/alp2401/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: true,
  },
  {
    productID: 1034325,
    productName: 'Urbas Love+ 24',
    productPrice: '650.000 VND',
    promotion: [],
    productColor: 'Oyster White',
    productSKU: 'ALP2402',
    productLabel: 'New Arrival',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ALP2402_1-1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ALP2402_5-1-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 140,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/alp2402/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: true,
  },
  {
    productID: 994533,
    productName: 'Pigment Tee - Nice Nature Club',
    productPrice: '390.000 VND',
    promotion: [],
    productColor: 'Greener Pastures',
    productSKU: 'AET00002',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AET00002_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AET00002_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 51,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/aet00002/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 988915,
    productName: 'Pigment Tee - AAA New Standard',
    productPrice: '390.000 VND',
    promotion: [],
    productColor: 'Kangaroo',
    productSKU: 'AET00001',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/pro_AET00001_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/pro_AET00001_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 52,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/aet00001/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 962345,
    productName: 'Vintas Public 2000s - Low Top',
    productPrice: '620.000 VND',
    promotion: {
      priceProduct: 620000,
      valuePromotion: 186000,
      priceAfterPromotion: 434000,
      textPriceAfterPromotion: '434.000 VND',
      textValuePromotion: '30 %',
      promotionID: 1046960,
    },
    productColor: 'Insignia Blue',
    productSKU: 'AV00207',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00207_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00207_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 367,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00207/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 962344,
    productName: 'Vintas Public 2000s - Low Top',
    productPrice: '620.000 VND',
    promotion: {
      priceProduct: 620000,
      valuePromotion: 124000,
      priceAfterPromotion: 496000,
      textPriceAfterPromotion: '496.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: 'Brindle',
    productSKU: 'AV00208',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00208_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00208_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 312,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00208/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 962343,
    productName: 'Vintas Public 2000s - Low Top',
    productPrice: '620.000 VND',
    promotion: {
      priceProduct: 620000,
      valuePromotion: 62000,
      priceAfterPromotion: 558000,
      textPriceAfterPromotion: '558.000 VND',
      textValuePromotion: '10 %',
      promotionID: 1046960,
    },
    productColor: 'Caviar Black',
    productSKU: 'AV00209',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00209_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00209_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 401,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00209/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 955079,
    productName: 'Hip Pack - Ananas Global Goal',
    productPrice: '275.000 VND',
    promotion: {
      priceProduct: 275000,
      valuePromotion: 55000,
      priceAfterPromotion: 220000,
      textPriceAfterPromotion: '220.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: 'Climbing Ivy',
    productSKU: 'AHP001',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHP001_1-1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHP001_10-1-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 24,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahp001/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 955078,
    productName: 'Hip Pack - Ananas Global Goal',
    productPrice: '275.000 VND',
    promotion: {
      priceProduct: 275000,
      valuePromotion: 55000,
      priceAfterPromotion: 220000,
      textPriceAfterPromotion: '220.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: 'Purple Sage',
    productSKU: 'AHP002',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHP002_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHP002_9-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 23,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahp002/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 955077,
    productName: 'Hip Pack - Ananas Global Goal',
    productPrice: '275.000 VND',
    promotion: {
      priceProduct: 275000,
      valuePromotion: 55000,
      priceAfterPromotion: 220000,
      textPriceAfterPromotion: '220.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: 'Blue Berry',
    productSKU: 'AHP003',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHP003_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHP003_9-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 15,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahp003/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 962410,
    productName: 'Urbas Love+ 23 - Slip On',
    productPrice: '550.000 VND',
    promotion: [],
    productColor: 'Offwhite',
    productSKU: 'ALP2023',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ALP2023_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ALP2023_7-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 0,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/alp2023/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: true,
  },
  {
    productID: 899186,
    productName: 'Vintas Vivu - Low Top',
    productPrice: '620.000 VND',
    promotion: {
      priceProduct: 620000,
      valuePromotion: 62000,
      priceAfterPromotion: 558000,
      textPriceAfterPromotion: '558.000 VND',
      textValuePromotion: '10 %',
      promotionID: 1046960,
    },
    productColor: 'Warm Sand',
    productSKU: 'AV00205',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00205_1-500x500.jpeg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00205_2-500x500.jpeg',
      ],
      type: 'jpeg',
    },
    statusQuantity: 399,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00205/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 899185,
    productName: 'Vintas Vivu - Low Top',
    productPrice: '620.000 VND',
    promotion: {
      priceProduct: 620000,
      valuePromotion: 186000,
      priceAfterPromotion: 434000,
      textPriceAfterPromotion: '434.000 VND',
      textValuePromotion: '30 %',
      promotionID: 1046960,
    },
    productColor: 'Plantation',
    productSKU: 'AV00206',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00206_1-500x500.jpeg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00206_2-500x500.jpeg',
      ],
      type: 'jpeg',
    },
    statusQuantity: 359,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00206/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919438,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Cinnamon Stick',
    productSKU: 'AHCS010',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS010_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS010_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 5,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs010/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919439,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Purple Passion',
    productSKU: 'AHCS009',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS009_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS009_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 19,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs009/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919440,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Cadmium Green',
    productSKU: 'AHCS008',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS008_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS008_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 1,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs008/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919441,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Sunny Lime',
    productSKU: 'AHCS007',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS007_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS007_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 29,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs007/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919442,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Black Beauty',
    productSKU: 'AHCS006',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS006_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS006_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 16,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs006/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919443,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Marshmallow',
    productSKU: 'AHCS005',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS005_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS005_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 47,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs005/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919436,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Laurel Oak',
    productSKU: 'AHCS012',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS012_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS012_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 0,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs012/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 919437,
    productName: 'High Crew Socks - Ananas Daily Things',
    productPrice: '95.000 VND',
    promotion: [],
    productColor: 'Candy Pink',
    productSKU: 'AHCS011',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AHCS011_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_AHCS011_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 19,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/ahcs011/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 924648,
    productName: 'Ananas "Copy" Store Bag 002',
    productPrice: '280.000 VND',
    promotion: {
      priceProduct: 280000,
      valuePromotion: 56000,
      priceAfterPromotion: 224000,
      textPriceAfterPromotion: '224.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: 'Caviar Black',
    productSKU: 'ASTB002',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_ASTB002_1-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Pro_ASTB002_2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 18,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/astb002/',
    category: 'Accessories | Phụ kiện',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 899187,
    productName: 'Vintas Nauda EXT - High Top',
    productPrice: '720.000 VND',
    promotion: {
      priceProduct: 720000,
      valuePromotion: 144000,
      priceAfterPromotion: 576000,
      textPriceAfterPromotion: '576.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: "Monk's Robe",
    productSKU: 'AV00204',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00204_1-500x500.jpeg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00204_2-500x500.jpeg',
      ],
      type: 'jpeg',
    },
    statusQuantity: 278,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00204/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 775846,
    productName: 'Vintas Nauda EXT - Low Top',
    productPrice: '650.000 VND',
    promotion: {
      priceProduct: 650000,
      valuePromotion: 130000,
      priceAfterPromotion: 520000,
      textPriceAfterPromotion: '520.000 VND',
      textValuePromotion: '20 %',
      promotionID: 1046960,
    },
    productColor: "Monk's Robe",
    productSKU: 'AV00203',
    productLabel: 'Sale off',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Pro_AV00203_1-500x500.jpeg',
        'https://ananas.vn/wp-content/uploads/Pro_AV00203_2-500x500.jpeg',
      ],
      type: 'jpeg',
    },
    statusQuantity: 334,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/av00203/',
    category: 'Footwear | Lên chân',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 823071,
    productName: 'Graphic Tee - Dance Till Sunrise',
    productPrice: '350.000 VND',
    promotion: [],
    productColor: 'Jet Black',
    productSKU: 'AGT0023',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Thumbnail-2-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Hover-2-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 9,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/agt0023/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 823070,
    productName: 'Graphic Tee - The Guitar Sings',
    productPrice: '350.000 VND',
    promotion: [],
    productColor: 'Jet Black',
    productSKU: 'AGT0024',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Thumbnail-3-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Hover-3-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 11,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/agt0024/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
  {
    productID: 829826,
    productName: 'Graphic Tee - 3 Days To Remember',
    productPrice: '350.000 VND',
    promotion: [],
    productColor: 'Vibrant Orange',
    productSKU: 'AGT0025',
    productLabel: '',
    media: {
      link: [
        'https://ananas.vn/wp-content/uploads/Thumbnail-5-500x500.jpg',
        'https://ananas.vn/wp-content/uploads/Hover-4-500x500.jpg',
      ],
      type: 'jpg',
    },
    statusQuantity: 22,
    isLike: false,
    linkBuyNow: 'https://ananas.vn/product-detail/agt0025/',
    category: 'Top | Nửa trên',
    isBuyOnline: false,
    isLimitedEdition: false,
  },
];
